import { getSupabaseServer } from '@realty-engine/core';
import SocialCalendarClient from './social-client';

export const dynamic = 'force-dynamic';

async function getProjects() {
  const supabase = getSupabaseServer();
  const { data } = await supabase
    .from('projects')
    .select('id, name, location')
    .order('created_at', { ascending: false });
  return data ?? [];
}

async function getPosts(projectId?: string) {
  const supabase = getSupabaseServer();
  let q = supabase
    .from('social_posts')
    .select('*, projects(name)')
    .order('scheduled_at', { ascending: true });
  if (projectId) q = q.eq('project_id', projectId);
  const { data } = await q.limit(200);
  return data ?? [];
}

export default async function SocialPage({
  searchParams,
}: {
  searchParams: { project?: string };
}) {
  const projects = await getProjects();
  const selected = searchParams.project ?? projects[0]?.id ?? '';
  const posts = await getPosts(selected || undefined);

  return (
    <div className="p-8">
      <div className="mb-6">
        <h1 className="text-2xl font-semibold tracking-tight text-white">Social Calendar</h1>
        <p className="text-sm text-gray-400 mt-1">
          Auto-generated by Claude. Approve to schedule via your configured provider.
        </p>
      </div>

      <SocialCalendarClient projects={projects} initialPosts={posts} initialProjectId={selected} />
    </div>
  );
}
