import { getSupabaseServer } from '@realty-engine/core';
import SocialCalendarClient from './social-client';

export const dynamic = 'force-dynamic';

async function getProjects() {
  const supabase = getSupabaseServer();
  const { data } = await supabase
    .from('projects')
    .select('id, name, location')
    .order('created_at', { ascending: false });
  return data ?? [];
}

async function getPosts(projectId?: string) {
  const supabase = getSupabaseServer();
  let q = supabase
    .from('social_posts')
    .select('*, projects(name)')
    .order('scheduled_at', { ascending: true });
  if (projectId) q = q.eq('project_id', projectId);
  const { data } = await q.limit(200);
  return data ?? [];
}

export default async function SocialPage({
  searchParams,
}: {
  searchParams: { project?: string };
}) {
  const projects = await getProjects();
  const selected = searchParams.project ?? projects[0]?.id ?? '';
  const posts = await getPosts(selected || undefined);

  return (
    <div className="p-6 md:p-8" style={{ backgroundColor: '#000' }}>
      <div className="mb-8 flex items-start justify-between gap-4">
        <div>
          <p
            className="text-[11px] font-bold uppercase tracking-[0.28em]"
            style={{ color: '#D4AF37' }}
          >
            Social
          </p>
          <h1 className="mt-1.5 text-2xl font-black tracking-tight text-white">
            Content Calendar
          </h1>
          <p className="mt-1 text-[14px] text-gray-500">
            Auto-generated by Claude · Approve to schedule via your configured provider
          </p>
        </div>
      </div>

      <SocialCalendarClient projects={projects} initialPosts={posts} initialProjectId={selected} />
    </div>
  );
}
