-- Media assets generated by Higgsfield for ad creatives.
-- creative_id references campaigns(id) — in this codebase the "campaign" row stores both
-- the campaign metadata AND the associated creative copy (headline/primary_text/etc).
CREATE TABLE ad_creative_media (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  creative_id uuid REFERENCES campaigns(id) ON DELETE CASCADE NOT NULL,
  type text NOT NULL CHECK (type IN ('image', 'video')),
  url text NOT NULL,
  generation_id text,
  status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'ready', 'failed')),
  error text,
  provider text NOT NULL DEFAULT 'higgsfield',
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_ad_creative_media_creative ON ad_creative_media(creative_id);

ALTER TABLE ad_creative_media ENABLE ROW LEVEL SECURITY;
CREATE POLICY "all" ON ad_creative_media FOR ALL USING (true);

-- Audit log for all incoming webhooks (Bolna, AiSensy, Meta, etc.)
CREATE TABLE webhook_events (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  provider text NOT NULL,
  event_type text,
  signature_valid boolean,
  raw_body jsonb,
  headers jsonb,
  processed_at timestamptz,
  error text,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_webhook_events_provider_created ON webhook_events(provider, created_at DESC);

ALTER TABLE webhook_events ENABLE ROW LEVEL SECURITY;
CREATE POLICY "all" ON webhook_events FOR ALL USING (true);

-- Higgsfield asset IDs and Meta Lead Ads form ID on campaigns
ALTER TABLE campaigns
  ADD COLUMN IF NOT EXISTS image_asset_id text,
  ADD COLUMN IF NOT EXISTS video_asset_id text,
  ADD COLUMN IF NOT EXISTS lead_form_id text;
